# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.24.0
  hooks:
  - id: eslint
  args:
  - --fix
        # additional_dependencies:
        #     -   eslint-config-google@0.7.1
        # -   babel-eslint@6.1.2
        # -   eslint-plugin-react@6.10.3
        # -   eslint@4.15.0
        # -   eslint-loader@1.6.1
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2
